name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Setup gotestfmt
        uses: gotesttools/gotestfmt-action@v2

      - name: Run tests with gotestfmt
        run: |
          set -euo pipefail
          make testjsonfmt 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Upload test log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
